var menu = [
    //Main Dishes
    {
        id: 0,
        title: "Chicken and Rice (KawMunKai)",
        category: "Main Dish",
        price: 50,
        img: "./img/hero3.png",
        desc: `Hot boiled chicken and steamy white rice.`,
        quantity: 0,
      },
      {
        id: 1,
        title: "Fried Chicken and Rice (KawMunKaiTod)",
        category: "Main Dish",
        price: 55,
        img: "./img/hero2.jpeg",
        desc: `Crispy fried chicken with steamy white rice.`,
        quantity: 0,
      },
      {
        id: 2,
        title: "Fried and Boiled Chicken with Rice (KawMunKaiRuam)",
        category: "Main Dish",
        price: 60,
        img: "./img/hero4.jpg",
        desc: `Hot boiled Chicken and Fried Chicken with steamy white Rice.`,
        quantity: 0,
      },
      {
        id: 3,
        title: "Fried Chicken (KaiTod)",
        category: "Main Dish",
        price: 70,
        img: "./img/hero5.jpg",
        desc: `Crispy Fried Chicken`,
        quantity: 0,
      },
      {
        id: 4,
        title: "Boiled Chicken (KaiTom)",
        category: "Main Dish",
        price: 70,
        img: "./img/hero6.jpg",
        desc: `Hot steamy juicy Chicken`,
        quantity: 0,
      },
      //Side Dishes
      {
        id: 5,
        title: "Chicken Gizzard",
        category: "Side Dish",
        price: 40,
        img: "./img/hero7.jpg",
        desc: `Chewy Chicken Gizzard`,
        quantity: 0,
      },
      {
        id: 6,
        title: "Chicken Stock Soup",
        category: "Side Dish",
        price: 15,
        img: "./img/hero8.jpg",
        desc: `Hot and Heart Warming Chicken Stock Soup`,
        quantity: 0,
      },
      {
        id: 7,
        title: "Boiled Chicken (KaiTom)",
        category: "Main Dish",
        price: 70,
        img: "./img/hero6.jpg",
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
        quantity: 0,
      },
      {
        id: 8,
        title: "Boiled Chicken (KaiTom)",
        category: "Main Dish",
        price: 70,
        img: "./img/hero6.jpg",
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
        quantity: 0,
      },
      {
        id: 9,
        title: "Boiled Chicken (KaiTom)",
        category: "Main Dish",
        price: 70,
        img: "./img/hero6.jpg",
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
        quantity: 0,
      },
]